name: Node.js Docker CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and test via Docker
      run: docker build --target tester -t test-todo-api-node .
      
    - name: Build final Image
      run: docker build -t prod-todo-api-node .

    - name: Discord notification
      if: always() 
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: ${{ job.status == 'success' && 'info' || 'error' }}
        details: 'La pipeline du projet Todo-API est termin√©e !'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        description: |
          Statut : ${{ job.status }}
          Branche : ${{ github.ref_name }}
          Commit : ${{ github.event.head_commit.message }}
          Lien : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}