name: Node.js Docker CI

on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        default: true
        type: boolean
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx eslint 

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node-version }}"
          cache: "npm"
      - run: npm ci
      - run: npm test

  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test -- --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 5

  sonarcloud:
    runs-on: ubuntu-latest
    needs: code-coverage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=database/**

  security-and-build:
    runs-on: ubuntu-latest
    needs: [lint, test, sonarcloud]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build and Scan Image
        run: |
          docker build -t prod-todo-api-node:latest .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: "prod-todo-api-node:latest"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/prod-todo-api-node:latest

  deploy-production:
    runs-on: ubuntu-latest
    needs: security-and-build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  auto-recovery:
    needs: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: Check Production Health
        id: health_check
        run: |
          sleep 40
          curl -f https://todo-api-node-h7rm.onrender.com/health || echo "recovery=true" >> $GITHUB_OUTPUT
      
      - name: Auto-Restart on Failure
        if: steps.health_check.outputs.recovery == 'true'
        run: |
          echo "Health check failed. Triggering recovery deploy..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  smoke-test:
    runs-on: ubuntu-latest
    needs: auto-recovery
    steps:
      - name: En attente que Render se d√©ploie (30s)
        run: sleep 30
      - name: Test acc√®s √† l'API sur Render
        run: |
          URL="https://todo-api-node-h7rm.onrender.com/"
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)
          if [ $STATUS -eq 200 ]; then
            echo "‚úÖ Succ√®s : L'API r√©pond 200"
          else
            echo "‚ùå Erreur : L'API r√©pond $STATUS"
            exit 1
          fi

  rollback:
    needs: deploy-production
    if: failure() 
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Rollback on Render
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/rollback \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"reason": "Automation: Deployment job failed"}'

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-production, rollback]
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Get Commit Details
        id: vars
        run: |
          echo "sha_short=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          echo "commit_msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Discord Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: ${{ needs.deploy-production.result == 'success' && 'info' || (needs.rollback.result == 'success' && 'warn' || 'error') }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Render Deploy Bot"
          title: "üöÄ Rapport de D√©ploiement Production"
          description: |
            **Statut final** : `${{ needs.deploy-production.result == 'success' && 'SUCCESS ‚úÖ' || 'FAILED ‚ùå' }}`
            
            **D√©tails du Commit**
            - **Auteur** : `${{ github.actor }}`
            - **Message** : `${{ steps.vars.outputs.commit_msg }}`
            - **Lien** : [${{ steps.vars.outputs.sha_short }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            
            **Environnement**
            - **Rollback activ√©** : `${{ needs.rollback.result == 'success' && 'OUI ‚ö†Ô∏è' || 'NON' }}`
            
            [Voir les logs GitHub Actions](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})